baseurl: https://www.nomnomz.nl
languageCode: nl-nl
title: Nomnomz.nl
theme: ananke
uglyURLs: true
enableRobotsTXT: true
copywrite: Geert & Margot
defaultContentLanguage: nl

menu:
  main:
    - identifier: recepten
      name: Recepten
      url: /recepten.html
      weight: 10
    - identifier: ingredienten
      name: Ingredienten
      url: /ingredienten.html
      weight: 20

taxonomies:
  ingredient: ingredienten

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml

params: {}
