baseurl: https://www.nomnomz.nl
languageCode: nl-nl
title: Nomnomz.nl
theme: ananke
uglyURLs: true
enableRobotsTXT: true
copywrite: Geert & Margot
defaultContentLanguage: nl

sectionPagesMenu: "main"

taxonomies:
  ingredient: ingredienten

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml

params: {}
